In [1]:
from utils import load_cddd_encoder

import torch
import _codecs
import numpy as np

# torch.serialization.add_safe_globals([np.dtypes.Int64DType, _codecs.encode, np.core.multiarray.scalar])


# cddd_enc = load_cddd_encoder('1k_test/models/cddd_encoder.pt')
cddd_enc = load_cddd_encoder('600k_chembl_float16/models/cddd_encoder.pt', weights_only=False)
cddd_enc

CDDDEncoder(
  (encoder): Encoder(
    (gru1): GRU(56, 512, batch_first=True)
    (gru2): GRU(512, 1024, batch_first=True)
    (gru3): GRU(1024, 2048, batch_first=True)
    (dropout): Dropout(p=0.15, inplace=False)
    (latent_projection): Linear(in_features=3584, out_features=512, bias=True)
    (gaussian_noise): GaussianNoise()
  )
)

In [2]:
for k,v in cddd_enc.encoder.state_dict().items():
    print(k, v.dtype)
# cddd_enc.encoder.to(torch.bfloat16)

gru1.weight_ih_l0 torch.bfloat16
gru1.weight_hh_l0 torch.bfloat16
gru1.bias_ih_l0 torch.bfloat16
gru1.bias_hh_l0 torch.bfloat16
gru2.weight_ih_l0 torch.bfloat16
gru2.weight_hh_l0 torch.bfloat16
gru2.bias_ih_l0 torch.bfloat16
gru2.bias_hh_l0 torch.bfloat16
gru3.weight_ih_l0 torch.bfloat16
gru3.weight_hh_l0 torch.bfloat16
gru3.bias_ih_l0 torch.bfloat16
gru3.bias_hh_l0 torch.bfloat16
latent_projection.weight torch.bfloat16
latent_projection.bias torch.bfloat16


In [4]:
cddd_enc(['CO', 'CN'])

(2, 512)

In [9]:
import torch

checkpoint = torch.load("600k_chembl_float16/checkpoints/last.ckpt", map_location="cpu", weights_only=True)
for key, val in checkpoint.items():
    print(key, val.dtype if hasattr(val, 'dtype') else type(val))
    # checkpoint[key] = checkpoint[key].to(torch.bfloat16)
# model.load_state_dict(checkpoint)

epoch <class 'int'>
global_step <class 'int'>
pytorch-lightning_version <class 'str'>
state_dict <class 'collections.OrderedDict'>
loops <class 'dict'>
callbacks <class 'dict'>
optimizer_states <class 'list'>
lr_schedulers <class 'list'>
hparams_name <class 'str'>
hyper_parameters <class 'dict'>


In [13]:
for k, v in checkpoint['state_dict'].items():
    print(k, v.dtype if hasattr(v, 'dtype') else type(v))

model.encoder.gru1.weight_ih_l0 torch.bfloat16
model.encoder.gru1.weight_hh_l0 torch.bfloat16
model.encoder.gru1.bias_ih_l0 torch.bfloat16
model.encoder.gru1.bias_hh_l0 torch.bfloat16
model.encoder.gru2.weight_ih_l0 torch.bfloat16
model.encoder.gru2.weight_hh_l0 torch.bfloat16
model.encoder.gru2.bias_ih_l0 torch.bfloat16
model.encoder.gru2.bias_hh_l0 torch.bfloat16
model.encoder.gru3.weight_ih_l0 torch.bfloat16
model.encoder.gru3.weight_hh_l0 torch.bfloat16
model.encoder.gru3.bias_ih_l0 torch.bfloat16
model.encoder.gru3.bias_hh_l0 torch.bfloat16
model.encoder.latent_projection.weight torch.bfloat16
model.encoder.latent_projection.bias torch.bfloat16
model.decoder.latent_to_states.weight torch.bfloat16
model.decoder.latent_to_states.bias torch.bfloat16
model.decoder.gru1.weight_ih_l0 torch.bfloat16
model.decoder.gru1.weight_hh_l0 torch.bfloat16
model.decoder.gru1.bias_ih_l0 torch.bfloat16
model.decoder.gru1.bias_hh_l0 torch.bfloat16
model.decoder.gru2.weight_ih_l0 torch.bfloat16
model.d

{'epoch': 27,
 'global_step': 110012,
 'pytorch-lightning_version': '2.5.0.post0',
 'state_dict': OrderedDict([('model.encoder.gru1.weight_ih_l0',
               tensor([[ 0.1040,  0.0366, -0.0104,  ...,  0.0332,  0.0347, -0.0410],
                       [-0.1016, -0.0008,  0.0347,  ...,  0.0302,  0.0664, -0.0635],
                       [ 0.0557, -0.0413, -0.0291,  ..., -0.0292,  0.0312,  0.0461],
                       ...,
                       [ 0.0771, -0.0264,  0.0267,  ..., -0.0302, -0.0618, -0.0330],
                       [-0.0625, -0.0143,  0.0204,  ..., -0.0282, -0.0339,  0.0410],
                       [ 0.0840, -0.0090,  0.0287,  ...,  0.0260,  0.0530, -0.0654]],
                      dtype=torch.bfloat16)),
              ('model.encoder.gru1.weight_hh_l0',
               tensor([[ 0.0308, -0.0153,  0.0381,  ...,  0.0203,  0.0173,  0.0300],
                       [ 0.0571, -0.0432,  0.0295,  ..., -0.0615, -0.0515,  0.0493],
                       [-0.0170, -0.0272, -0.026

In [3]:
cddd_enc(['CO', 'CN'])

array([[ 0.453125  , -0.9140625 , -0.421875  , ...,  0.78125   ,
         0.875     , -0.8203125 ],
       [ 0.44921875, -0.9375    , -0.3046875 , ...,  0.82421875,
         0.83984375, -0.7734375 ]], dtype=float32)

In [5]:
import pandas as pd

df = pd.read_csv('data/600k_chembl_filtered.smi.zst', header=None, names=['smiles'])
print(df.info())
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636218 entries, 0 to 636217
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   smiles  636218 non-null  object
dtypes: object(1)
memory usage: 4.9+ MB
None


smiles
0  CC1(C)CCC(C)(C)c2cc(-c3cccc(-c4ccc(C(=O)O)cc4)...
1  Cc1cc2c(cc1C1=NOC(c3ccc(C(=O)O)cc3)C1)C(C)(C)C...
2  Cc1ccc(-c2ccc(C(=O)O)cc2)cc1-c1ccc2c(c1)C(C)(C...
3  Cc1cc2c(cc1-c1ncc(-c3ccc(C(=O)O)cc3)s1)C(C)(C)...
4  Cc1ccc(-c2ccc(C(=O)O)cc2)cc1-c1cc2c(cc1C)C(C)(...
5  Cc1cc2c(cc1-c1cccc(-c3ccc(C(=O)O)cc3)n1)C(C)(C...
6  CC1(C)CCC(C)(C)c2cc(-c3cccc(-c4ccc(C(=O)O)cc4)...
7  CC1(C)CCC(C)(C)c2cc(-c3ccc4cc(C(=O)O)ccc4c3)ccc21
8   CC(=Cc1ccc(C(=O)O)cc1)c1ccc2c(c1)C(C)(C)CCC2(C)C
9  CC(C)=C(c1ccc(C(=O)O)cc1)c1ccc2c(c1)C(C)(C)CCC...

In [4]:
df.sample(1000).to_csv('data/1k_test.smi', index=False, header=False)

In [8]:
cddd_enc(df.smiles.sample(1000))

array([[ 0.38867188, -0.55078125,  0.45703125, ...,  0.16503906,
        -0.27539062, -0.12207031],
       [ 0.42578125,  0.37304688,  0.453125  , ..., -0.95703125,
        -0.37109375,  0.90625   ],
       [-0.47460938, -0.07714844, -0.640625  , ..., -0.87890625,
        -0.8046875 ,  0.296875  ],
       ...,
       [ 0.11132812,  0.921875  ,  0.75      , ..., -0.77734375,
        -0.859375  ,  0.78515625],
       [ 0.62109375, -0.38085938,  0.671875  , ..., -0.03979492,
        -0.48242188,  0.81640625],
       [ 0.1953125 ,  0.38671875,  0.5390625 , ..., -0.9140625 ,
        -0.5390625 ,  0.88671875]], dtype=float32)